name: build and test

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-site]
  push:
  pull_request:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --remote --recursive --init
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm install
    - run: npm run build
      env:
         GH_PAGES_BUILD: true
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
